FROM gcc:latest

RUN apt-get update && apt-get install -y cmake


COPY /src/Model /app/src/Model
COPY /src/Controller /app/src/Controller
COPY /src/Tests /app/src/Tests


RUN cd /app/src/Model
RUN ls


COPY CMakeLists.txt /app
WORKDIR /app/

RUN mkdir data

RUN mkdir build
WORKDIR /app/build/

RUN cmake .. && make

CMD ["./runServer"]